### ISSUE TITLE
Update dependences

### ISSUE THREAD

**Issue by pac1006** [pac1006/GESPRO_GESTIONVERSIONES#2]
- Check if it's possible to use v13 support library instead of v4.
- Update Realm to 3.0.0
- Permission Utils
 http://martiancraft.com/blog/2015/06/android-support-library/ https://github.com/davidmigloz/go-bees/issues/190

**Comment by arroyofe** [comment]
Modification made on 4 files needing update. See detail on referenced commit.

**Comment by arroyofe** [comment]
Issue closed
